package damjay.publicity.omnipost.scheduler;

import damjay.publicity.omnipost.data.entity.Member;
import java.util.ArrayList;
import java.util.List;

/** Built-in alumni birthday roster. Column A = January, rows = days. */
public final class AlumniRoster {
  private AlumniRoster() {}

  public static List<Member> members() {
    List<Member> out = new ArrayList<>();
    add(out, "Adetunji Bakinson", 5, 1);
    add(out, "Ebiniyi Janet", 5, 1);
    add(out, "Fakiya Victor", 9, 1);
    add(out, "Abiodun Williams", 1, 2);
    add(out, "Omojowogbe Taiwo", 2, 2);
    add(out, "Adeite Subomi", 3, 2);
    add(out, "Folajimi Kalejaye", 6, 2);
    add(out, "Daniel-Anthony Glory", 3, 3);
    add(out, "Olamide Omole", 5, 3);
    add(out, "Adejoro Toluwanimi", 5, 3);
    add(out, "Adetona Israel", 6, 3);
    add(out, "Dolapo Olorunda", 6, 3);
    add(out, "Stephen Oriyomi", 7, 3);
    add(out, "Jesupelumi Awopetu", 9, 3);
    add(out, "Adebowale Ifeoluwa Esther", 9, 3);
    add(out, "Michael Stifler Peter", 10, 3);
    add(out, "Adekunle Adejumo", 10, 3);
    add(out, "Adeotun Adeyemi", 1, 4);
    add(out, "Blossom Oluwaloju Irinyemi", 4, 4);
    add(out, "Divine Babatunde", 8, 4);
    add(out, "Bello Tolulope", 3, 5);
    add(out, "Oluwatobi Oyetunde", 3, 5);
    add(out, "Omodasola Omotosho", 3, 5);
    add(out, "Success Aladetan", 5, 5);
    add(out, "Faith Idebumi", 5, 5);
    add(out, "Adeola Shodunke", 9, 5);
    add(out, "Johnson Fiyinfoluwa", 10, 5);
    add(out, "Pemi Bello", 11, 5);
    add(out, "Ayanfeoluwa (Ogunsola) Oluwatunwase Victoria", 3, 6);
    add(out, "Babatunde Adebo", 6, 6);
    add(out, "Omotayo Omopariwa", 7, 6);
    add(out, "Oluwatumininu Ologunsua", 10, 6);
    add(out, "Onabanjo Gboyega Adewole", 11, 6);
    add(out, "Obiyemi Iyanuoluwa", 1, 7);
    add(out, "Akinde Omogbolahan", 11, 7);
    add(out, "Damilare Odukoya", 11, 7);
    add(out, "Oladepo Esther", 5, 8);
    add(out, "Abimbola Precious", 5, 8);
    add(out, "Patrick Okeule", 5, 8);
    add(out, "Olanlere Temidayo", 6, 8);
    add(out, "Samuel Adediwura", 6, 8);
    add(out, "Izuagie Ruth Oghenero", 6, 8);
    add(out, "Oluwabukade Ojediran nee Fasogbon", 8, 8);
    add(out, "Opeyemi Oluwalogbon", 8, 8);
    add(out, "Obatoke Deborah", 11, 8);
    add(out, "Akinsola Oladunni Agnes", 11, 8);
    add(out, "David Precious Imeobong", 12, 8);
    add(out, "Adedoyin Adeyeye", 2, 9);
    add(out, "oluwadara Temitayo", 4, 9);
    add(out, "Adewoyin Olufemi", 6, 9);
    add(out, "Michael Tunji Ekpeti", 6, 9);
    add(out, "Ubaka Amazinggrace Abiodun-Ojo Oluwaferanmi", 6, 9);
    add(out, "Toluwanimi Oyeniyi", 8, 9);
    add(out, "Mojubaoluwa Oladowa", 12, 9);
    add(out, "Akeju Korede Joseph", 2, 10);
    add(out, "Akinwande Samuel", 2, 10);
    add(out, "Fatuase Olatunji Oladeke", 2, 10);
    add(out, "Toluwanimi Owofadeju", 8, 10);
    add(out, "Tosin Aromolaran", 9, 10);
    add(out, "Ifeoluwa Bodunde", 9, 10);
    add(out, "Oluwatomisin Ogunbanjo", 10, 10);
    add(out, "Beauty Ewere", 2, 11);
    add(out, "Ayomide Adedeji", 3, 11);
    add(out, "Omotosho Temitope", 7, 11);
    add(out, "Onyenche Akinyele", 12, 11);
    add(out, "Agunbiade Temidara", 2, 12);
    add(out, "Mark Duke", 3, 12);
    add(out, "Ilori Oluwatofunmi Elizabeth", 8, 12);
    add(out, "Amos Fortune", 10, 12);
    add(out, "Esther Ilerioluwa Olujuwon", 10, 12);
    add(out, "Adegboye Toluwalase", 10, 12);
    add(out, "Durowoju Isaac", 10, 12);
    add(out, "Obisesan Kunle", 10, 12);
    add(out, "Olubisi Albert ADETUNJI", 10, 12);
    add(out, "Osalor Wonderful Eva", 11, 12);
    add(out, "Akinade Akintomiwa", 11, 12);
    add(out, "Opeyemi Osho", 2, 13);
    add(out, "Gbemisola Doubra-Omomo", 2, 13);
    add(out, "Ibukunnlaoluwa Olushola", 5, 13);
    add(out, "Olawuyi Mercy Temiloluwa", 5, 13);
    add(out, "Adeyi Christglory", 11, 13);
    add(out, "Oluwapelumi Oladapo", 1, 14);
    add(out, "Adewuyi Oluwafunmilayo", 1, 14);
    add(out, "Animashaun Obaloluwa", 1, 14);
    add(out, "Georgeana Reuben", 5, 14);
    add(out, "Shina-Tawose Damilare", 5, 14);
    add(out, "Fadipe Yota", 8, 14);
    add(out, "Ann", 11, 14);
    add(out, "Awopetu Jesubukunmi", 1, 15);
    add(out, "Ifeoluwa Olorunda", 3, 15);
    add(out, "Alo Esther", 4, 15);
    add(out, "Blessing Oyewunmi", 4, 15);
    add(out, "Tolulope Odunaya", 4, 15);
    add(out, "Oby Nwadioha", 5, 15);
    add(out, "Adeaga Oluwaseun", 8, 15);
    add(out, "Femi Wilhelm", 8, 15);
    add(out, "Ademisoye Peace", 9, 15);
    add(out, "Paseda Samuel", 10, 15);
    add(out, "Utibeima Udo", 11, 15);
    add(out, "Omotola Oshunmakinde", 6, 16);
    add(out, "Ayobami Adetiba", 7, 16);
    add(out, "Adegunle Gideon Gbenga", 8, 16);
    add(out, "Akinade Happiness Oyinkansola", 9, 16);
    add(out, "Salmon Delight Oyinkansola", 10, 16);
    add(out, "Aluko Tomilola", 1, 17);
    add(out, "Kolawole Ayooluwa Samuel", 3, 17);
    add(out, "Omotosho Peter", 5, 17);
    add(out, "Boluwatife", 7, 17);
    add(out, "Ojo Abigail Oluwatoyin", 12, 17);
    add(out, "Odiakose Is well Boluwatife", 1, 18);
    add(out, "Agunmaro Mitchell", 7, 18);
    add(out, "Bamgbose Timilehin", 9, 18);
    add(out, "Adeyemi Emmanuel", 10, 18);
    add(out, "Omolayo Otaiku", 1, 19);
    add(out, "Akindele Tobiloba", 1, 19);
    add(out, "Babalola Gideon", 2, 19);
    add(out, "Iyiola Ibilola", 2, 19);
    add(out, "Omodele Samuel", 3, 19);
    add(out, "Oluwadare A. Hassan", 6, 19);
    add(out, "Bukola Latinwo", 7, 19);
    add(out, "Busayo Amoo", 7, 19);
    add(out, "Temiloluwa Awopeju", 8, 19);
    add(out, "Opeyemi Onilude", 9, 19);
    add(out, "Henry Yissa", 9, 19);
    add(out, "Mayowa Idowu", 10, 19);
    add(out, "Olusegun Omilabi", 6, 20);
    add(out, "Anjolajesu Omotosho", 11, 20);
    add(out, "Sao Oluwaseun", 12, 20);
    add(out, "Ugonnaya Ada Priscilla", 2, 21);
    add(out, "Dan-John Chibuzor Daniel", 6, 21);
    add(out, "Olaoye Samuel", 8, 21);
    add(out, "Ajayi Temidayo", 10, 21);
    add(out, "Damilola Olanrewaju", 1, 22);
    add(out, "Lasisi Akinkunmi", 2, 22);
    add(out, "Ifedayo Tolulope", 2, 22);
    add(out, "Ayanfeoluwa Omotosho", 3, 22);
    add(out, "Akinyemi-Akinwande Oluwatunmise", 5, 22);
    add(out, "Julia Ndame", 9, 22);
    add(out, "Kemi Adebo", 9, 22);
    add(out, "Akintayo Motolani", 12, 22);
    add(out, "Olatunji Olaronke", 12, 22);
    add(out, "Folarin Oluwaseun", 3, 23);
    add(out, "Jeffrey Ugorji", 3, 23);
    add(out, "Sonibare Oluwadamilola", 5, 23);
    add(out, "Sowunmi Kehinde", 5, 23);
    add(out, "Gideon Adepoju", 6, 23);
    add(out, "Alowolodu Joseph Adebusayo", 10, 23);
    add(out, "Oluwatobi Daniel-Aremu nee Adebusuyi", 10, 23);
    add(out, "Odunayo Oyeleke", 10, 23);
    add(out, "James Adebayo", 11, 23);
    add(out, "Agunbiade Titilayo Hadassah", 1, 24);
    add(out, "Morakinyo Tomisin", 2, 24);
    add(out, "Victoria Esimekhuai", 2, 24);
    add(out, "Esther Oluwapelumi Daniel", 4, 24);
    add(out, "Oluwadare Oladimeji", 5, 24);
    add(out, "Odunowo Opeyemi", 7, 24);
    add(out, "Okunade Eunice Oluwatofunmi", 7, 24);
    add(out, "Taofeek Ayomide", 7, 24);
    add(out, "Titilayomi Johnson", 8, 24);
    add(out, "Ayooluwa Oguntade", 8, 24);
    add(out, "Deji Adeoye", 12, 24);
    add(out, "Zino Afemari", 3, 25);
    add(out, "Adeniyi Ayodeji Felix", 3, 25);
    add(out, "Ubaka Favour", 6, 25);
    add(out, "Faith Timothy-Hassan", 7, 25);
    add(out, "Odupitan Abolaji Abraham", 8, 25);
    add(out, "Olumide Adaramoye", 9, 25);
    add(out, "Oshinloye Oluwatoyin", 9, 25);
    add(out, "Goodness Omodele", 9, 25);
    add(out, "David Adeosun", 10, 25);
    add(out, "Oni Tomiwa", 1, 26);
    add(out, "Olajuwon Opeoluwa James", 2, 26);
    add(out, "Aderounmu Ayopo", 3, 26);
    add(out, "Ade-Onojobi Taiwo", 4, 26);
    add(out, "Villumsen Joan", 5, 26);
    add(out, "Arogundade Olamide", 5, 26);
    add(out, "Azeez Yetunde", 6, 26);
    add(out, "Caroline Chidiebere Obi", 7, 26);
    add(out, "Bello Samson", 7, 26);
    add(out, "Samuel Bodunrin", 7, 26);
    add(out, "Arogundade Philip", 8, 26);
    add(out, "Motunrayo Gongul", 8, 26);
    add(out, "Boluwatife Animashaun", 8, 26);
    add(out, "Oyinkansola Adekoya", 10, 26);
    add(out, "Salu Mopelola", 12, 26);
    add(out, "Ojo Oluwatosin", 3, 27);
    add(out, "Omogbeni Dideoluwa", 3, 27);
    add(out, "Ojo Joy", 5, 27);
    add(out, "Akinmola Opemipo", 5, 28);
    add(out, "Oyeleke Ruth Gbemisola", 7, 28);
    add(out, "Adeyemi Joseph Tolulope", 8, 28);
    add(out, "Adetutu Oladayo", 8, 28);
    add(out, "Also Nicole Oluwatimilehin", 9, 28);
    add(out, "Oyegunju Oluwagbemisola", 9, 28);
    add(out, "Kanyinsola Abajesude", 12, 28);
    add(out, "Aremu Oluwatosin", 3, 29);
    add(out, "Olayinka Okesiji", 5, 29);
    add(out, "Onyinyechi Okereke", 5, 29);
    add(out, "Oluwatobi Ademosu", 6, 29);
    add(out, "Lawal Oluwadamilare", 6, 29);
    add(out, "Badejoko Oluwatomiwa", 7, 29);
    add(out, "Ehis Esther", 7, 29);
    add(out, "Aladetan Victor", 8, 29);
    add(out, "Medinat Oyedele", 9, 29);
    add(out, "Boye Ogunleye", 9, 29);
    add(out, "Alao Victoria", 9, 29);
    add(out, "Solomon Oluwamayowa", 9, 29);
    add(out, "Ibukunoluwa Ajala", 10, 29);
    add(out, "Famutimi Victor", 10, 29);
    add(out, "Owofadeju Inioluwa", 10, 29);
    add(out, "Oluwaseyi Abiodun-Ojo", 11, 29);
    add(out, "Michael Ogundijo", 11, 29);
    add(out, "Animashaun Israel", 1, 30);
    add(out, "Ejere Emmanuel", 3, 30);
    add(out, "Kolawole Oluwatosimi", 4, 30);
    add(out, "Mba Uka", 9, 30);
    add(out, "Olanrewaju Isaac Oludare", 12, 30);
    add(out, "Temitope Oyedeji", 3, 31);
    add(out, "Oluwabori Shobayo", 3, 31);
    add(out, "Samuel Aduroja", 5, 31);
    add(out, "Amaka A", 5, 31);
    add(out, "Agunmaro Funmilayo", 12, 31);
    return out;
  }

  public static int size() {
    return 222;
  }

  private static void add(List<Member> out, String name, int month, int day) {
    Member member = new Member();
    member.name = name;
    member.birthMonth = month;
    member.birthDay = day;
    member.kind = Member.KIND_ALUMNI;
    member.skipCaption = true;
    member.notes = "alumni-roster";
    out.add(member);
  }
}

